CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id_user SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    firstname VARCHAR,
    society VARCHAR,
    password VARCHAR NOT NULL,
    email VARCHAR,
    admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL,
    last_conn TIMESTAMPTZ DEFAULT NULL
);
INSERT INTO users (name,firstname,society,password,email,admin)
VALUES ('Dupond','Fred','LECLIENT',crypt('MDP_Admin_123', gen_salt('bf')),'fred.admin@leclient.fr',TRUE),
       ('Nzengue','Daouda','LECLIENT',crypt('MDP_Admin_456', gen_salt('bf')),'daouda.nzengue@leclient.fr',TRUE),
       ('Pierre','Rubens','Capgemini',crypt('MDP_User_123', gen_salt('bf')),'rubens.pierre@capgemini.fr',FALSE),
       ('Rivière','Sophie','SAP',crypt('MDP_User_234', gen_salt('bf')),'sophie.r@sap.fr',FALSE),
       ('Ziae Yekta','Amith','Salesforce',crypt('MDP_User_345', gen_salt('bf')),'amith.ziae_yekta@salesforce.com',FALSE),
       ('Lombard','Michel','Thales',crypt('MDP_User_456', gen_salt('bf')),'michellombard@thales.fr',FALSE);

CREATE TABLE qcm (
    id_qcm SERIAL PRIMARY KEY,
    title VARCHAR NOT NULL,
    description VARCHAR,
    created_by INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL
);
INSERT INTO qcm (title,description,created_by)
VALUES ('Java','Test de connaissance sur le langage Java',2),
       ('Python débutant','Test de connaissance sur le langage python pour les débutants',1),
       ('Angular','Test de connaissance sur le framework Angular',2),
       ('PHP','Test de connaissance sur le langage PHP',2),
       ('JavaScript','Test de connaissance sur le langage JavaScript',1),
       ('NodeJS','Test de connaissance sur la plateforme de développement JavaScript NodeJS',2);

CREATE TABLE question_qcm (
    id_question SERIAL PRIMARY KEY,
    id_qcm INTEGER,
    question VARCHAR NOT NULL,
    type VARCHAR(8) CHECK (type IN ('single', 'multiple')) DEFAULT 'single',
    position INTEGER,
    created_by INTEGER,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL,
    FOREIGN KEY (id_qcm) REFERENCES qcm(id_qcm)
); 
INSERT INTO question_qcm (id_qcm,question,type,position,created_by)
VALUES (1,'Java est un langage ...','single',1,2),
       (1,'Quel mot-clé permet de définir une classe en Java ?','single',2,2),
       (1,'Quel est le nom du point d’entrée d’une application Java ?','single',3,2),
       (1,'Quel type est utilisé pour les nombres à virgule en Java ?','multiple',4,2),
       (1,'Que fait le ramasse-miettes (Garbage Collector) en Java ?','single',5,2),
       (1,'Java est principalement…','single',6,2),
       (1,'Quel mot-clé permet d’hériter d’une classe ?','single',7,2),
       (1,'Une interface en Java peut contenir…','single',8,2),
       (1,'Quel outil compile les fichiers .java en bytecode ?','single',9,2),
       (1,'Est ce que JVM (Java Virtual Machine) exécute le bytecode Java sur la machine hôte ?','single',10,2),
       (2,'Quelle est la bonne façon de déclarer une variable en Python ?','single',1,1),
       (2,'Quelle fonction permet d’afficher du texte à l’écran ?','single',2,1),
       (2,'Comment écrire un commentaire en Python ?','single',3,1),
       (2,'Quel type de boucle est utilisé pour répéter un bloc un nombre fixe de fois ?','single',4,1),
       (2,'Que fait l’instruction len("Python") ?','single',5,1),
       (2,'Quel symbole est utilisé pour l’exponentiation (puissance) en Python ?','single',6,1),
       (2,'Quelle est la sortie de ce code ? x,y = 5,3  print(x % y)','single',7,1),
       (2,'Quelle est la différence entre une liste et un tuple en Python ?','single',8,1),
       (2,'Comment définir une fonction en Python ?','single',9,1),
       (2,'Quelle méthode permet d’ajouter un élément à la fin d’une liste ?','single',10,1),
       (3,'Quel est le rôle du décorateur @Component ?','single',1,2),
       (3,'Dans Angular, ngOnInit est utilisé pour :','single',2,2),
       (3,'Les directives structurelles modifient :','multiple',3,2),
       (3,'Lequel de ces éléments fait partie du système de routage Angular ?','multiple',4,2),
       (3,'Parmi ces options, lesquelles sont des types de liaison de données Angular ?','multiple',5,2),
       (3,'Quel est le rôle d’un service dans Angular ?','single',6,2),
       (3,'Quelles sont les manières d’injecter un service dans un composant Angular ?','multiple',7,2),
       (3,'Lequel de ces modules est essentiel pour utiliser les formulaires réactifs dans Angular ?','single',8,2),
       (3,'Quelle est la différence principale entre un Observable et une Promise ?','single',9,2),
       (3,'Parmi ces pipes Angular, lesquels sont intégrés par défaut ?','multiple',10,2),
       (3,'Lequel des éléments suivants peut-on utiliser pour créer un module Angular ?','multiple',11,2),
       (3,'Quels avantages apporte le lazy loading dans Angular ?','multiple',12,2),
       (4,'Comment démarre et termine un bloc de code PHP ?','single',1,2),
       (4,'Quelle fonction PHP permet d’afficher du texte à l’écran ?','single',2,2),
       (5,'Quelle instruction permet d’afficher un message dans la console du navigateur ?','single',1,1),
       (5,'Comment déclare-t-on une variable en JavaScript moderne ?','single',2,1),
       (6,'Quel module Node.js est utilisé pour créer un serveur HTTP simple ?','single',1,2),
       (6,'Quelle commande permet d’installer un package Node.js depuis npm ?','single',2,2);

CREATE TABLE response_question (
    id_response SERIAL PRIMARY KEY,
    id_question INTEGER,
    response VARCHAR,
    is_correct BOOLEAN,
    position INTEGER,
    FOREIGN KEY (id_question) REFERENCES question_qcm(id_question)
);
INSERT INTO response_question (id_question, response, is_correct, position)
VALUES (1,'interprété',FALSE,1),
    (1,'compilé',FALSE,2),
    (1,'les deux',TRUE,3),
    (2,'function',FALSE,1),
    (2,'class',TRUE,2),
    (2,'object',FALSE,3),
    (3,'main',TRUE,1),
    (3,'master',FALSE,2),
    (4,'int',FALSE,1),
    (4,'float',TRUE,2),
    (4,'double',TRUE,3),
    (5,'Il supprime les variables inutilisées de la mémoire',TRUE,1),
    (5,'Il trie le code source',FALSE,2),
    (5,'Il compile le bytecode',FALSE,3),
    (6,'Orienté objet',TRUE,1),
    (6,'Fonctionnel',FALSE,2),
    (6,'Procédural',FALSE,3),
    (7,'extends',TRUE,1),
    (7,'inherits',FALSE,2),
    (7,'super',FALSE,3),
    (8,'Des attributs avec valeurs',FALSE,1),
    (8,'Des méthodes abstraites',TRUE,2),
    (8,'Du code exécutable avant Java 8',FALSE,3),
    (9,'java',FALSE,1),
    (9,'javac',TRUE,2),
    (9,'jvm',FALSE,3),
    (10,'vrai',TRUE,1),
    (10,'faux',FALSE,2),
    (11,'var x = 10',FALSE,1),
    (11,'x = 10',TRUE,2),
    (11,'int x = 10',FALSE,3),
    (11,'let x = 10',FALSE,4),
    (12,'echo("Bonjour")',FALSE,1),
    (12,'print("Bonjour")',TRUE,2),
    (12,'printf("Bonjour")',FALSE,3),
    (12,'display("Bonjour")',FALSE,4),
    (13,'<!-- Ceci est un commentaire -->',FALSE,1),
    (13,'// Ceci est un commentaire',FALSE,2),
    (13,'# Ceci est un commentaire',TRUE,3),
    (13,'# Ceci est un commentaire',FALSE,4),
    (14,'while',FALSE,1),
    (14,'for',TRUE,2),
    (14,'repeat',FALSE,3),
    (14,'loop',FALSE,4),
    (15,'Retourne 0',FALSE,1),
    (15,'Retourne "Python"',FALSE,2),
    (15,'Retourne 6',TRUE,3),
    (15,'Retourne 7',FALSE,4),
    (16,'^',FALSE,1),
    (16,'**',TRUE,2),
    (16,'*',FALSE,3),
    (16,'%',FALSE,4),
    (17,'2',TRUE,1),
    (17,'1',FALSE,2),
    (17,'3',FALSE,3),
    (17,'5',FALSE,4),
    (18,'Une liste est immuable, un tuple est modifiable',FALSE,1),
    (18,'Une liste est modifiable, un tuple est immuable',TRUE,2),
    (18,'Les deux sont immuables',FALSE,3),
    (18,'Les deux sont modifiables',FALSE,4),
    (19,'function ma_fonction():',FALSE,1),
    (19,'def ma_fonction():',TRUE,2),
    (19,'fun ma_fonction():',FALSE,3),
    (19,'define ma_fonction():',FALSE,4),
    (20,'append()',TRUE,1),
    (20,'add()',FALSE,2),
    (20,'insert()',FALSE,3),
    (20,'extend()',FALSE,4),
    (21,'Définir un service injectable',FALSE,1),
    (21,'Déclarer une directive',FALSE,2),
    (21,'Définir un composant Angular',TRUE,3),
    (21,'Définir un module Angular',FALSE,4),
    (22,'Détruire un composant',FALSE,1),
    (22,'Initialiser le composant après l’initialisation des propriétés d’entrée',TRUE,2),
    (22,'Mettre à jour le DOM automatiquement',FALSE,3),
    (22,'Gérer les services injectés',FALSE,4),
    (23,'La structure du DOM',TRUE,1),
    (23,'Les styles CSS',FALSE,2),
    (23,'Le comportement du DOM',TRUE,3),
    (24,'RouterModule',TRUE,1),
    (24,'Routes',TRUE,2),
    (24,'NgModule',FALSE,3),
    (24,'RouterLink',TRUE,4),
    (25,'Liaison unidirectionnelle (interpolation)',TRUE,1),
    (25,'Liaison bidirectionnelle ([(ngModel)])',TRUE,2),
    (25,'Liaison événementielle ((click))',TRUE,3),
    (25,'Liaison CSS directe',FALSE,4),
    (26,'Fournir une logique métier réutilisable',TRUE,1),
    (26,'Définir un composant visuel',FALSE,2),
    (26,'Remplacer les modules',FALSE,3),
    (26,'Gérer uniquement les événements du DOM',FALSE,4),
    (27,'Via le constructeur du composant',TRUE,1),
    (27,'Via le décorateur @Injectable',TRUE,2),
    (27,'En utilisant ngOnInit',FALSE,3),
    (27,'En important directement le fichier du service',FALSE,4),
    (28,'FormsModule',FALSE,1),
    (28,'ReactiveFormsModule',TRUE,2),
    (28,'HttpClientModule',FALSE,3),
    (29,'Une Promise peut émettre plusieurs valeurs',FALSE,1),
    (29,'Un Observable peut émettre plusieurs valeurs dans le temps',TRUE,2),
    (29,'Une Promise est paresseuse et ne s’exécute que lorsqu’on l’abonne',FALSE,3),
    (30,'DatePipe',TRUE,1),
    (30,'CurrencyPipe',TRUE,2),
    (30,'CustomPipe',FALSE,3),
    (30,'UpperCasePipe',TRUE,4),
    (31,'@NgModule',TRUE,1),
    (31,'@Component',FALSE,2),
    (31,'imports',TRUE,3),
    (31,'declarations',TRUE,4),
    (32,'Réduction du temps de chargement initial',TRUE,1),
    (32,'Chargement conditionnel des modules',TRUE,2),
    (32,'Permet d’éviter d’utiliser les composants',FALSE,3),
    (32,'Amélioration de la performance globale de l’application',TRUE,4),
    (33,'<php ... ?>',FALSE,1),
    (33,'<?php ... ?>',TRUE,2),
    (33,'<? ... ?>',FALSE,3),
    (33,'<script> ... </script>',FALSE,4),
    (34,'echo',TRUE,1),
    (34,'printText',FALSE,2),
    (34,'display',FALSE,3),
    (34,'write',FALSE,4),
    (35,'print("Hello")',FALSE,1),
    (35,'console.log("Hello")',TRUE,2),
    (35,'echo("Hello")',FALSE,3),
    (35,'echo("Hello")',FALSE,4),
    (36,'variable x = 5;',FALSE,1),
    (36,'var x = 5;',TRUE,2),
    (36,'let x = 5;',TRUE,3),
    (36,'int x = 5;',FALSE,4),
    (37,'fs',FALSE,1),
    (37,'http',FALSE,2),
    (37,'url',FALSE,3),
    (37,'express',TRUE,4),
    (38,'node install <package>;',TRUE,1),
    (38,'npm add <package>',FALSE,2),
    (38,'npm add <package>',FALSE,3),
    (38,'node get <package>',FALSE,4);

CREATE TABLE quiz_attempts (
    id_attempt SERIAL PRIMARY KEY,
    id_qcm INTEGER,
    id_user INTEGER,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    completed FLOAT,
    score FLOAT,
    FOREIGN KEY (id_qcm) REFERENCES qcm(id_qcm),
    FOREIGN KEY (id_user) REFERENCES users(id_user)
);
INSERT INTO quiz_attempts (id_qcm,id_user,started_at,ended_at,completed,score)
VALUES (1,4,'2025-09-16 17:24:42.02395+02','2025-09-16 17:24:52.00425+02',0,0),
       (3,3,'2025-09-16 17:14:15.45213+02','2025-09-16 17:27:17.14528+02',75,25),
       (3,4,'2025-09-16 16:45:18.45276+02','2025-09-16 16:55:35.45722+02',100,100);

CREATE TABLE user_answers (
    id_attempt INTEGER,
    id_question INTEGER,
    id_response INTEGER,
    PRIMARY KEY (id_attempt, id_question,id_response)
);
INSERT INTO user_answers (id_attempt,id_question,id_response)
VALUES (2,21,71),
       (2,22,75),
       (2,23,77),
       (2,23,79),
       (2,24,80),
       (2,24,81),
       (2,27,93),
       (2,28,97),
       (2,29,100),
       (2,30,102),
       (2,30,103),
       (2,30,104),
       (2,31,106),
       (2,31,107),
       (2,31,108),
       (3,21,71),
       (3,22,74),
       (3,23,77),
       (3,23,79),
       (3,24,80),
       (3,24,81),
       (3,24,83),
       (3,25,84),
       (3,25,85),
       (3,25,86),
       (3,26,88),
       (3,27,92),
       (3,27,93),
       (3,28,97),
       (3,29,100),
       (3,30,102),
       (3,30,103),
       (3,30,105),
       (3,31,106),
       (3,31,108),
       (3,31,109),
       (3,32,110),
       (3,32,111),
       (3,32,113);